### ISSUE TITLE
Some Ideas.. :)

### ISSUE THREAD

**Issue by Berndinox** [bluedigits/iota-node#13]
Some Ideas:

From what i understand the iri.ini is loaded dynmicly while its runnin, would it be possible to echo new neighboars and/or the neighbors file into it.
Searching for a way not to restart the containert but to add new neighboars or to remove them

Also a swtich for  "--revalidate" would be fine, sometimes you have to rescan your DB if things are broken or so.

Keep up the good work ,BR

**Comment by Berndinox** [comment]
Added revalidate Option: https://github.com/bluedigits/iota-node/pull/14

**Comment by nimearo** [comment]
> From what i understand the iri.ini is loaded dynmicly while its runnin, would it be possible to echo new neighboars and/or the neighbors file into it.
Searching for a way not to restart the containert but to add new neighboars or to remove them
Sure such a thing is possible and you might adapt the scripts from bin folder in the source repository on your docker host to dynamically add neighbors to your node. They use API call via curl and append to neighbors file in volumes files on the host. This works quite ok for a small setup.
Nevertheless I prefer some kind of management interface like ipm for this. But I didn't found out yet if ipm can permanently change neighbors list to survive restarts.
> Also a swtich for "--revalidate" would be fine, sometimes you have to rescan your DB if things are broken or so.
You can already append additional options at the end of your run command. In my opinion there no need to add a variable for each option in the Dockerfile

**Comment by bluedigits** [comment]
>>Also a swtich for "--revalidate" would be fine, sometimes you have to rescan your DB if things are broken or so.

>You can already append additional options at the end of your run command. In my opinion there no need to add a variable for each option in the Dockerfile
Exactly! Just add --revalidate to the end of your command chain! In case of docker-compose you could do something similar to: https://docs.docker.com/compose/compose-file/#args

**Comment by bluedigits** [comment]
@Berndinox This can be closed, right? :)
