### ISSUE TITLE
Node doesn't sync

### ISSUE THREAD

**Issue by 1two3code** [bluedigits/iota-node#15]
I got the node running but it seems to be out of sync and not willing to sync.
I've been looking around but I can't seem to find any way to get it to work. It seems that it should work out of the box inside the docker... o.O

getNodeInfo via the API gives me this:
```json
{
    "appName": "IRI",
    "appVersion": "1.4.1.2",
    "jreAvailableProcessors": 6,
    "jreFreeMemory": 2033435648,
    "jreVersion": "9.0.1",
    "jreMaxMemory": 4294967296,
    "jreTotalMemory": 2147483648,
    "latestMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    "latestMilestoneIndex": 243000,
    "latestSolidSubtangleMilestone": "999999999999999999999999999999999999999999999999999999999999999999999999999999999",
    "latestSolidSubtangleMilestoneIndex": 243000,
    "neighbors": 4,
    "packetsQueueSize": 0,
    "time": 1511298083529,
    "tips": 0,
    "transactionsToRequest": 0,
    "duration": 1
}
```

Any ideas?

**Comment by nimearo** [comment]
You may check the logs of iri in your running container and see if it shows any errors which may cause this behaviour.

The command below for example will show you the logs since one minute and will update the log afterwards.
> docker logs --since 1m -f $containerId

Additionally you may check getNeighbors API call to see if you receive transactions from any neighbor at all.

**Comment by bluedigits** [comment]
How do you run your docker container? Can you please give the whole command you're invoking?

What about the `netstat -lntpu` output? Are the ports listening on your host machine as expected?

**Comment by Berndinox** [comment]
Hy, got similar issues, my solution was:

sudo sysctl -w net.ipv6.conf.all.forwarding=1
add "--rescan" command when restating the container with a mounted volume for the DB
had to restart the container 2 or 3 times to until i get in sync

BR

**Comment by 1two3code** [comment]
Sorry, I've been busy so I haven't been able to reply yet,
I'll get back to you during the week after I've tried Berndinox's solution.

**Comment by 1two3code** [comment]
Berndinox solution worked!
It seems to have been solved (at least for TCP) by forwarding for ipv6 and publishing ports with the -p argument on docker run command.

Thank you so much!

**Comment by bluedigits** [comment]
@thepill yeah good idea!

I'm gonna close this as nobody else seems to have syncing issues.
