### ISSUE TITLE
Being able to specify ports...

### ISSUE THREAD

**Issue by docbill** [bluedigits/iota-node#2]
It would be useful to be able to specify which ports the container listens to inside the container.  As either a command line option or environmental variable.

As an example of why this is needed, I originally started with iota running under windows with the default ports of 14265, 14600, and 15600 respectively.   When transitioning to this docker container instead, initially I thought it would be sufficient to change the forwarding in my router...

It turns out though at least of TCP-IP, iota will send the connecting host back the internal port number.   So clients would connect to 15600 and then get a redirect to port 15777 on the same address.  At that point my router would drop the connection on the floor.

I added an entry to also forward port 15777 to port 15777 on my server.   That mostly worked.   But some people need to configure the outgoing port and address in their firewall.   So they would add port 15600 and again the connection would get dropped on the floor.

UDP seems less problematic, but it is also harder to see if some of the traffic is being lost from the port mis-match.

The other problem with not being able to specify the port is because IRI seems to depend on the internal and external ports being identical, it means only a single docker container instance can work behind a NAT firewall.

**Comment by docbill** [comment]
BTW.  If you would like I could send a pull request.  But I suspect this is the type of update you'd like to make in your own way, as I would be likely to completely rewrite things rather than making a small delta.

**Comment by bluedigits** [comment]
Hey Bill,

Thank you for your detailed explanation of the problem. Now I understand why it's not sufficient to just change the exposed Docker ports. Much appreciated. I would be thrilled if you could open a pull request because I'm on vacation starting from tomorrow.

Thank you in advance for your efforts!

Best,
Merlin

**Comment by bluedigits** [comment]
Hey Bill,

I made the ports configurable from outside. Is it sufficient now? I will close this ticket.

**Comment by docbill** [comment]
Hi Merlin,

Thanks, this completely slipped mind.
