### ISSUE TITLE
New IRI!

### ISSUE THREAD

**Issue by Berndinox** [bluedigits/iota-node#20]
An Update is needed, may just a rebuild will do it! Could you kick in?

https://github.com/iotaledger/iri/releases/tag/v1.4.1.4

BR

**Comment by bluedigits** [comment]
Yes, of course :) Normally, this get's done automatically as soon as they merge the release into master branch. But this time, I will do it manually.

**Comment by bluedigits** [comment]
[X] Done :)

**Comment by Berndinox** [comment]
:) thanks
