### ISSUE TITLE
Stuck Milestone

### ISSUE THREAD

**Issue by Berndinox** [bluedigits/iota-node#21]
With the last Version my Milestones always got stuck.

When restartinig it displays 243000 for some time. During this time it seems like it's loading new milestone, but when it jumps over to the correct one, then this milestone does not change anymore.

It's now on 309753 / 309942 - Node Milestone (309753) is not increasing anymore
Restart Container
It's 24300 / 24300 for half an hour.
Then 309945 / 310003 - (309945 is not increasing anymore)

Whats wrong? My neighboars are fine, did work with the Version before.

**Comment by bluedigits** [comment]
Can't help with this one as this is related to IRI. But I know, that the IRI devs are already aware of this and working hard to fix this issue.

Please see: https://github.com/iotaledger/iri/issues/428

**Comment by brunoamancio** [comment]
Many people, including me, have the same issue. Still waiting for a solution, as this is a critical fix.

**Comment by bluedigits** [comment]
Me too, hopefully this gets fixed soon in IRI by the team of @iotaledger

**Comment by bluedigits** [comment]
@brunoamancio @Berndinox since the new IRI version 1.4.1.6 is out, do you have still issues with milestones getting stuck?

**Comment by brunoamancio** [comment]
No issues with it anymore. The logic change there was to remove the part with the problem, since it was not so meaningful. Other part of the code ends up making the removed part not so relevant. That is the Ostrich algorithm's philosophy :)
