### ISSUE TITLE
cannot stop iota-node

### ISSUE THREAD

**Issue by framlin** [bluedigits/iota-node#23]
I have always this error-message, if I try to stop the container:

#docker stop iota-node
Error response from daemon: cannot stop container: iota-node: Cannot kill container a4793f11834d62e63ebbfadf43cca9c422c086345497d41bed74572bbdcc2e23: connection error: desc = "transport: dial unix /var/run/docker/containerd/docker-containerd.sock: connect: connection refused": unknown

Is this a problem of this concete container, or do I have an issue with my docker installation?
I use an ubuntu 16.04 server to run the container.

**Comment by nimearo** [comment]
Which user did you used for executing the command?

**Comment by framlin** [comment]
root

**Comment by bluedigits** [comment]
For me it looks like you're having a problem with connecting to your docker daemon. Can you please run  and stop some other docker container to see if it's iota-node specific?

**Comment by bluedigits** [comment]
I'm going to close this one, because there's apparently no longer a problem.
