### ISSUE TITLE
Question: Automatic builds on Docker Hub

### ISSUE THREAD

**Issue by pr4xx** [bluedigits/iota-node#7]
Hey there, this is not an issue but a question:
How often does this image get rebuild for docker hub? Since the last pull request, the dockerfile includes the latest iri by default. Before that, we used to update the dockerfile manually with each new release. So at which time does docker hub update the image? Is it commit based or by interval? If it is only commit based, the docker image won't get any updates by its own.

**Comment by bluedigits** [comment]
Hi Nico,

Thank you for your message. Indeed, a really good question. I configured the docker hub repository to automatically trigger a build of the container when the official iotaledger/iri github repository has changed. I will keep an eye onto this issue to make sure that the iota-node container build gets automatically triggered when needed.

Thank you again, Nico, for the hint.

Best wishes,
Merlin

**Comment by bluedigits** [comment]
I think, this will be OK for now.
